name: cypress-typescript-cucumber
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: 'dependency install'
        run: npm install
        env:
          CI: true
      - name: test
        run: npm run test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: cucumber_report/html/cucumber_report.html

